### PR TITLE
Update of bg.json

### PR DESCRIPTION
**Pull request by Petarkir2000**
Some stylistic improvement.

### CODE REVIEW

**Review by ohheyitsdave — APPROVED** [review]

**Comment by ohheyitsdave** [comment]
Hi @Petarkir2000, thanks again. 
Just to let you now, we now have multilingual assembly guide. 
Currently just 4 languages (de, en, fr, sk). Could you help us to have it also available in bg?

**Comment by Petarkir2000** [comment]
Of course @ohheyitsdave. I really want to help for the translator of the page. Could you give me the link to this guide? I want to translate the guidance for sensor assembly but I couldn’t find the source...

**Comment by Petarkir2000** [comment]
PS. Have a look on our BG page as well : https://airbg.info/en/how-to/

**Comment by ohheyitsdave** [comment]
It's easy. Inside `/content/airrohr/` just copy the `en` folder, rename it to `bg` and translate all the markdown files. You don't have to rename the files. Just the content of the markdown files. 
And some smaller changes need to be done, but will update the documentation soon.

**Comment by ohheyitsdave** [comment]
I see you have also a few more detailed information. We have some of those in the troublshoot guide, but not that detailed as yours 😅

**Comment by Petarkir2000** [comment]
Hello @ohheyitsdave , I have pulled request for /content/airrohr/bg for Bulgarian content/airrohr. However I found that the Footer has "IMPORTANT LINKS" to be translated. Where can I find the file?

**Comment by ohheyitsdave** [comment]
updated the `/locales/en.json` with the missing strings. You can find it line 134 and 143.

**Comment by Petarkir2000** [comment]
I have translated those lines(134-143) in bg.json, but on the site are shown "Maps/API/Archive/Devices/Forum", not "Sitemap/License/Connect/Blog..."

**Comment by ohheyitsdave** [comment]
Hi @Petarkir2000, we have a new footer design which is more compact than the previous one. So some items like license, blog, connect,... were currently removed.

**Pull request merged**
