### PR TITLE
Feature/french translation

### PR DESCRIPTION
**Pull request by pjgueno**

### CODE REVIEW

**Comment by pjgueno** [comment]
Is it here?

**Comment by ricki-z** [comment]
It's the right place but it seems like files in /static/ were also changed. These files are the same for all languages...

**Comment by pjgueno** [comment]
I tried to correct. I am quite puzzled because I didn't modified any of the png... What should I do?

**Comment by ricki-z** [comment]
You can "reset" the files to the last commit by discarding your changes (maybe something only changed a timestamp or attribute).
If you use the GUI client: right click on the file, choose "Discard changes". 
On the command line: git checkout -- FILE-NAME

**Comment by ohheyitsdave** [comment]
Hi @pjgueno, 

thanks again for you help :+1: 

There are two ways how to resolve the conflict.
**First:** can you copy your translations from `/content/airrohr/fr` files outside the project. Then `git clone` the project or `pull` the current HEAD, switch to `develop` branch and create a `feature/french-translation` branch and copy your md-files and PR again.
**Second:** way is to resolve the conflict by yourself, you could try rebase with the current base and then you have your changes on top and best way just your .md-files will be pushed.

Therefore I will close the PR and you can resubmit it again (guess that's the easiest and safest way). Hit me up via Mattermost if you need help.

**Pull request closed without merging**
