### PR TITLE
Feature/spanish translation

### PR DESCRIPTION
**Pull request by pjgueno**
Arnaud's translation. He corrected some stuff.

### CODE REVIEW

**Review by ohheyitsdave — CHANGES_REQUESTED** [review]
Hi @pjgueno, 
somehow the French files / pull request sneaked in. Can you remove the files or just create a new pull request with just the Spanish files? You can use `git add dir/filename.extension` or `git add dir/lang/*` to add just specific files.
Thanks

**Comment by pjgueno** [comment]
> somehow the French files / pull request sneaked in. Can you remove the files or just create a new pull request with just the Spanish files? You can use git add dir/filename.extension or git add dir/lang/* to add just specific files.

What do you mean ? I can see all the files EN/FR/ES in each place.

**Comment by pjgueno** [comment]
In this cas just take the file from my repo at @pjgueno and create the es ordner.

**Comment by pjgueno** [comment]
French removed. Should work

**Pull request closed without merging**
