### PR TITLE
Feature/portuguese translation

### PR DESCRIPTION
**Pull request by taffarel55**
### Feature/portuguese translation 🇵🇹 / 🇧🇷

Hello, first of all I would like to congratulate the project !! Very interesting, I would like to help with sensors here in Brazil. :heart_eyes:

But before that, I translated the repository according to the information in [README.md](https://github.com/opendata-stuttgart/sensor.community/blob/develop/README.md) into Portuguese. As I did not find a file in the repository indicating how to perform the pull request, I made 1 commit for each file update.

Please, if there are any changes to be made, please let me know! :smiley:

### CODE REVIEW

**Comment by ohheyitsdave** [comment]
thanks for your contribution @taffarel55 👏
Gonna checkout your commit.

**Comment by ohheyitsdave** [comment]
@taffarel55 looks good 😀 you added the DNMS endpoint in `routes\endpoints\dnms\pt\index.json.js` but the DNMS translation markdown file in`content\dnsm\pt\` are missing 😬 
Any chance you can add those? 

1. I can wait until you re-commit those files into this pull request
2. I'll release this, and you commit another pull request?

You can choose 😊

**Comment by taffarel55** [comment]
Yes, of course I can do it! :smiley:

Following `README.md` I didn't see that I had to edit the Markdown file in `content/dnsm/pt/` :joy:

You can release this and I will commit another pull request! ok?

**Comment by ohheyitsdave** [comment]
Good point, I will add the DNMS guide to the `README.md`!
And I will release your current pull request!

**Review by ohheyitsdave — APPROVED** [review]
🎉

**Comment by taffarel55** [comment]
Hello @ohheyitsdave! 

Has the site had significant content changes since my last PR? If so, please contact me and I'll update the translation :heart_eyes:.

**Comment by ohheyitsdave** [comment]
Hi @taffarel55, currently no changes have been done. Probably soon there will be an update, I'll let you know 🙂
Thanks 🙏

**Pull request merged**
