### PR TITLE
Bulgarian translation

### PR DESCRIPTION
**Pull request by Petarkir2000**
Bulgarian translation ready to import.

### CODE REVIEW

**Comment by ohheyitsdave** [comment]
Hi @Petarkir2000 , 
thanks for your help with the translation. 
You need to do some additional work in some files (`src/utils/initI18n.js`, `src/routes/[lang]/_layout.svelte`, `src/components/LanguageSwitcher.svelte`) so the translation is displayed on the website.
👉  https://github.com/opendata-stuttgart/sensor.community#translation

**Review by ohheyitsdave — CHANGES_REQUESTED** [review]
Hi @Petarkir2000 , 
thanks for your help with the translation. 
You need to do some additional work in some files (`src/utils/initI18n.js`, `src/routes/[lang]/_layout.svelte`, `src/components/LanguageSwitcher.svelte`) so the translation is displayed on the website.
👉  https://github.com/opendata-stuttgart/sensor.community#translation

**Review by ohheyitsdave — APPROVED** [review]

**Comment by ohheyitsdave** [comment]
Now everything looks good. Thanks again! :)

**Comment by Petarkir2000** [comment]
Thank You!

**Pull request merged**
